// import './instance/index'
// import './lifecyle/index'
// import './data-binding/index'
// import './computed/index'
// import './directive/index'
// import './computed/define'
import './computed/extend'
